spring:
  datasource:
    url: jdbc:h2:mem:tranzo_user_db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update   # automatically creates tables from your entities
    show-sql: true       # prints SQL queries in console

  h2:
    console:
      enabled: true      # allows web access to H2 console
      path: /h2-console  # the URL path for the H2 dashboard